// <auto-generated/>
#pragma warning disable CS0618
using CollegeFootballData.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace CollegeFootballData.Ppa.Players.Games
{
    /// <summary>
    /// Builds and executes requests for operations under \ppa\players\games
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GamesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::CollegeFootballData.Ppa.Players.Games.GamesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GamesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ppa/players/games?year={year}{&excludeGarbageTime*,playerId*,position*,seasonType*,team*,threshold*,week*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CollegeFootballData.Ppa.Players.Games.GamesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GamesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ppa/players/games?year={year}{&excludeGarbageTime*,playerId*,position*,seasonType*,team*,threshold*,week*}", rawUrl)
        {
        }
        /// <summary>
        /// Queries player PPA statistics by game
        /// </summary>
        /// <returns>A List&lt;global::CollegeFootballData.Models.PlayerGamePredictedPointsAdded&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::CollegeFootballData.Models.PlayerGamePredictedPointsAdded>?> GetAsync(Action<RequestConfiguration<global::CollegeFootballData.Ppa.Players.Games.GamesRequestBuilder.GamesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::CollegeFootballData.Models.PlayerGamePredictedPointsAdded>> GetAsync(Action<RequestConfiguration<global::CollegeFootballData.Ppa.Players.Games.GamesRequestBuilder.GamesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::CollegeFootballData.Models.PlayerGamePredictedPointsAdded>(requestInfo, global::CollegeFootballData.Models.PlayerGamePredictedPointsAdded.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Queries player PPA statistics by game
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::CollegeFootballData.Ppa.Players.Games.GamesRequestBuilder.GamesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::CollegeFootballData.Ppa.Players.Games.GamesRequestBuilder.GamesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::CollegeFootballData.Ppa.Players.Games.GamesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::CollegeFootballData.Ppa.Players.Games.GamesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::CollegeFootballData.Ppa.Players.Games.GamesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Queries player PPA statistics by game
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GamesRequestBuilderGetQueryParameters 
        {
            /// <summary>Optional flag to exclude garbage time plays</summary>
            [QueryParameter("excludeGarbageTime")]
            public bool? ExcludeGarbageTime { get; set; }
            /// <summary>Optional player ID filter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("playerId")]
            public string? PlayerId { get; set; }
#nullable restore
#else
            [QueryParameter("playerId")]
            public string PlayerId { get; set; }
#endif
            /// <summary>Optional player position abbreviation filter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("position")]
            public string? Position { get; set; }
#nullable restore
#else
            [QueryParameter("position")]
            public string Position { get; set; }
#endif
            /// <summary>Optional season type filter</summary>
            [Obsolete("This property is deprecated, use SeasonTypeAsSeasonType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("seasonType")]
            public string? SeasonType { get; set; }
#nullable restore
#else
            [QueryParameter("seasonType")]
            public string SeasonType { get; set; }
#endif
            /// <summary>Optional season type filter</summary>
            [QueryParameter("seasonType")]
            public global::CollegeFootballData.Models.SeasonType? SeasonTypeAsSeasonType { get; set; }
            /// <summary>Team filter, required if week not specified</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("team")]
            public string? Team { get; set; }
#nullable restore
#else
            [QueryParameter("team")]
            public string Team { get; set; }
#endif
            /// <summary>Threshold value for minimum number of plays</summary>
            [QueryParameter("threshold")]
            public double? Threshold { get; set; }
            /// <summary>Week filter, required if team not specified</summary>
            [QueryParameter("week")]
            public int? Week { get; set; }
            /// <summary>Required year filter</summary>
            [QueryParameter("year")]
            public int? Year { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GamesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::CollegeFootballData.Ppa.Players.Games.GamesRequestBuilder.GamesRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
