/*
 * College Football Data API
 *
 * This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.
 *
 * The version of the OpenAPI document: 5.6.8
 * Contact: admin@collegefootballdata.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CollegeFootballData.Model;
using CollegeFootballData.Client;
using System.Reflection;

namespace CollegeFootballData.Test.Model
{
    /// <summary>
    ///  Class for testing LiveGame
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LiveGameTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LiveGame
        //private LiveGame instance;

        public LiveGameTests()
        {
            // TODO uncomment below to create an instance of LiveGame
            //instance = new LiveGame();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LiveGame
        /// </summary>
        [Fact]
        public void LiveGameInstanceTest()
        {
            // TODO uncomment below to test "IsType" LiveGame
            //Assert.IsType<LiveGame>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Clock'
        /// </summary>
        [Fact]
        public void ClockTest()
        {
            // TODO unit test for the property 'Clock'
        }

        /// <summary>
        /// Test the property 'Possession'
        /// </summary>
        [Fact]
        public void PossessionTest()
        {
            // TODO unit test for the property 'Possession'
        }

        /// <summary>
        /// Test the property 'Teams'
        /// </summary>
        [Fact]
        public void TeamsTest()
        {
            // TODO unit test for the property 'Teams'
        }

        /// <summary>
        /// Test the property 'Drives'
        /// </summary>
        [Fact]
        public void DrivesTest()
        {
            // TODO unit test for the property 'Drives'
        }

        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Fact]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }

        /// <summary>
        /// Test the property 'Down'
        /// </summary>
        [Fact]
        public void DownTest()
        {
            // TODO unit test for the property 'Down'
        }

        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Fact]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }

        /// <summary>
        /// Test the property 'YardsToGoal'
        /// </summary>
        [Fact]
        public void YardsToGoalTest()
        {
            // TODO unit test for the property 'YardsToGoal'
        }
    }
}
