/*
 * College Football Data API
 *
 * This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.
 *
 * The version of the OpenAPI document: 5.6.10
 * Contact: admin@collegefootballdata.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CollegeFootballData.Model;
using CollegeFootballData.Client;
using System.Reflection;

namespace CollegeFootballData.Test.Model
{
    /// <summary>
    ///  Class for testing Matchup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MatchupTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Matchup
        //private Matchup instance;

        public MatchupTests()
        {
            // TODO uncomment below to create an instance of Matchup
            //instance = new Matchup();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Matchup
        /// </summary>
        [Fact]
        public void MatchupInstanceTest()
        {
            // TODO uncomment below to test "IsType" Matchup
            //Assert.IsType<Matchup>(instance);
        }

        /// <summary>
        /// Test the property 'Team1'
        /// </summary>
        [Fact]
        public void Team1Test()
        {
            // TODO unit test for the property 'Team1'
        }

        /// <summary>
        /// Test the property 'Team2'
        /// </summary>
        [Fact]
        public void Team2Test()
        {
            // TODO unit test for the property 'Team2'
        }

        /// <summary>
        /// Test the property 'Team1Wins'
        /// </summary>
        [Fact]
        public void Team1WinsTest()
        {
            // TODO unit test for the property 'Team1Wins'
        }

        /// <summary>
        /// Test the property 'Team2Wins'
        /// </summary>
        [Fact]
        public void Team2WinsTest()
        {
            // TODO unit test for the property 'Team2Wins'
        }

        /// <summary>
        /// Test the property 'Ties'
        /// </summary>
        [Fact]
        public void TiesTest()
        {
            // TODO unit test for the property 'Ties'
        }

        /// <summary>
        /// Test the property 'Games'
        /// </summary>
        [Fact]
        public void GamesTest()
        {
            // TODO unit test for the property 'Games'
        }

        /// <summary>
        /// Test the property 'StartYear'
        /// </summary>
        [Fact]
        public void StartYearTest()
        {
            // TODO unit test for the property 'StartYear'
        }

        /// <summary>
        /// Test the property 'EndYear'
        /// </summary>
        [Fact]
        public void EndYearTest()
        {
            // TODO unit test for the property 'EndYear'
        }
    }
}
