/*
 * College Football Data API
 *
 * This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.
 *
 * The version of the OpenAPI document: 5.6.19
 * Contact: admin@collegefootballdata.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CollegeFootballData.Model;
using CollegeFootballData.Client;
using System.Reflection;

namespace CollegeFootballData.Test.Model
{
    /// <summary>
    ///  Class for testing PlayerWeightedEPA
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlayerWeightedEPATests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PlayerWeightedEPA
        //private PlayerWeightedEPA instance;

        public PlayerWeightedEPATests()
        {
            // TODO uncomment below to create an instance of PlayerWeightedEPA
            //instance = new PlayerWeightedEPA();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PlayerWeightedEPA
        /// </summary>
        [Fact]
        public void PlayerWeightedEPAInstanceTest()
        {
            // TODO uncomment below to test "IsType" PlayerWeightedEPA
            //Assert.IsType<PlayerWeightedEPA>(instance);
        }

        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Fact]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }

        /// <summary>
        /// Test the property 'AthleteId'
        /// </summary>
        [Fact]
        public void AthleteIdTest()
        {
            // TODO unit test for the property 'AthleteId'
        }

        /// <summary>
        /// Test the property 'AthleteName'
        /// </summary>
        [Fact]
        public void AthleteNameTest()
        {
            // TODO unit test for the property 'AthleteName'
        }

        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }

        /// <summary>
        /// Test the property 'Team'
        /// </summary>
        [Fact]
        public void TeamTest()
        {
            // TODO unit test for the property 'Team'
        }

        /// <summary>
        /// Test the property 'Conference'
        /// </summary>
        [Fact]
        public void ConferenceTest()
        {
            // TODO unit test for the property 'Conference'
        }

        /// <summary>
        /// Test the property 'Wepa'
        /// </summary>
        [Fact]
        public void WepaTest()
        {
            // TODO unit test for the property 'Wepa'
        }

        /// <summary>
        /// Test the property 'Plays'
        /// </summary>
        [Fact]
        public void PlaysTest()
        {
            // TODO unit test for the property 'Plays'
        }
    }
}
