/*
 * College Football Data API
 *
 * This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.
 *
 * The version of the OpenAPI document: 5.6.12
 * Contact: admin@collegefootballdata.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CollegeFootballData.Model;
using CollegeFootballData.Client;
using System.Reflection;

namespace CollegeFootballData.Test.Model
{
    /// <summary>
    ///  Class for testing PlayerPPAChartItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlayerPPAChartItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PlayerPPAChartItem
        //private PlayerPPAChartItem instance;

        public PlayerPPAChartItemTests()
        {
            // TODO uncomment below to create an instance of PlayerPPAChartItem
            //instance = new PlayerPPAChartItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PlayerPPAChartItem
        /// </summary>
        [Fact]
        public void PlayerPPAChartItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" PlayerPPAChartItem
            //Assert.IsType<PlayerPPAChartItem>(instance);
        }

        /// <summary>
        /// Test the property 'PlayNumber'
        /// </summary>
        [Fact]
        public void PlayNumberTest()
        {
            // TODO unit test for the property 'PlayNumber'
        }

        /// <summary>
        /// Test the property 'AvgPPA'
        /// </summary>
        [Fact]
        public void AvgPPATest()
        {
            // TODO unit test for the property 'AvgPPA'
        }
    }
}
