/*
 * College Football Data API
 *
 * This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.
 *
 * The version of the OpenAPI document: 5.6.9
 * Contact: admin@collegefootballdata.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CollegeFootballData.Model;
using CollegeFootballData.Client;
using System.Reflection;

namespace CollegeFootballData.Test.Model
{
    /// <summary>
    ///  Class for testing PollRank
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PollRankTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PollRank
        //private PollRank instance;

        public PollRankTests()
        {
            // TODO uncomment below to create an instance of PollRank
            //instance = new PollRank();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PollRank
        /// </summary>
        [Fact]
        public void PollRankInstanceTest()
        {
            // TODO uncomment below to test "IsType" PollRank
            //Assert.IsType<PollRank>(instance);
        }

        /// <summary>
        /// Test the property 'School'
        /// </summary>
        [Fact]
        public void SchoolTest()
        {
            // TODO unit test for the property 'School'
        }

        /// <summary>
        /// Test the property 'Rank'
        /// </summary>
        [Fact]
        public void RankTest()
        {
            // TODO unit test for the property 'Rank'
        }

        /// <summary>
        /// Test the property 'Conference'
        /// </summary>
        [Fact]
        public void ConferenceTest()
        {
            // TODO unit test for the property 'Conference'
        }

        /// <summary>
        /// Test the property 'FirstPlaceVotes'
        /// </summary>
        [Fact]
        public void FirstPlaceVotesTest()
        {
            // TODO unit test for the property 'FirstPlaceVotes'
        }

        /// <summary>
        /// Test the property 'Points'
        /// </summary>
        [Fact]
        public void PointsTest()
        {
            // TODO unit test for the property 'Points'
        }
    }
}
