/*
 * College Football Data API
 *
 * This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.
 *
 * The version of the OpenAPI document: 5.6.17
 * Contact: admin@collegefootballdata.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CollegeFootballData.Model;
using CollegeFootballData.Client;
using System.Reflection;

namespace CollegeFootballData.Test.Model
{
    /// <summary>
    ///  Class for testing PollWeek
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PollWeekTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PollWeek
        //private PollWeek instance;

        public PollWeekTests()
        {
            // TODO uncomment below to create an instance of PollWeek
            //instance = new PollWeek();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PollWeek
        /// </summary>
        [Fact]
        public void PollWeekInstanceTest()
        {
            // TODO uncomment below to test "IsType" PollWeek
            //Assert.IsType<PollWeek>(instance);
        }

        /// <summary>
        /// Test the property 'Season'
        /// </summary>
        [Fact]
        public void SeasonTest()
        {
            // TODO unit test for the property 'Season'
        }

        /// <summary>
        /// Test the property 'SeasonType'
        /// </summary>
        [Fact]
        public void SeasonTypeTest()
        {
            // TODO unit test for the property 'SeasonType'
        }

        /// <summary>
        /// Test the property 'Week'
        /// </summary>
        [Fact]
        public void WeekTest()
        {
            // TODO unit test for the property 'Week'
        }

        /// <summary>
        /// Test the property 'Polls'
        /// </summary>
        [Fact]
        public void PollsTest()
        {
            // TODO unit test for the property 'Polls'
        }
    }
}
