/*
 * College Football Data API
 *
 * This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.
 *
 * The version of the OpenAPI document: 5.6.11
 * Contact: admin@collegefootballdata.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CollegeFootballData.Model;
using CollegeFootballData.Client;
using System.Reflection;

namespace CollegeFootballData.Test.Model
{
    /// <summary>
    ///  Class for testing PredictedPointsValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PredictedPointsValueTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PredictedPointsValue
        //private PredictedPointsValue instance;

        public PredictedPointsValueTests()
        {
            // TODO uncomment below to create an instance of PredictedPointsValue
            //instance = new PredictedPointsValue();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PredictedPointsValue
        /// </summary>
        [Fact]
        public void PredictedPointsValueInstanceTest()
        {
            // TODO uncomment below to test "IsType" PredictedPointsValue
            //Assert.IsType<PredictedPointsValue>(instance);
        }

        /// <summary>
        /// Test the property 'YardLine'
        /// </summary>
        [Fact]
        public void YardLineTest()
        {
            // TODO unit test for the property 'YardLine'
        }

        /// <summary>
        /// Test the property 'PredictedPoints'
        /// </summary>
        [Fact]
        public void PredictedPointsTest()
        {
            // TODO unit test for the property 'PredictedPoints'
        }
    }
}
