/*
 * College Football Data API
 *
 * This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.
 *
 * The version of the OpenAPI document: 5.6.23
 * Contact: admin@collegefootballdata.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CollegeFootballData.Model;
using CollegeFootballData.Client;
using System.Reflection;

namespace CollegeFootballData.Test.Model
{
    /// <summary>
    ///  Class for testing Recruit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RecruitTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Recruit
        //private Recruit instance;

        public RecruitTests()
        {
            // TODO uncomment below to create an instance of Recruit
            //instance = new Recruit();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Recruit
        /// </summary>
        [Fact]
        public void RecruitInstanceTest()
        {
            // TODO uncomment below to test "IsType" Recruit
            //Assert.IsType<Recruit>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'RecruitType'
        /// </summary>
        [Fact]
        public void RecruitTypeTest()
        {
            // TODO unit test for the property 'RecruitType'
        }

        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Fact]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Stars'
        /// </summary>
        [Fact]
        public void StarsTest()
        {
            // TODO unit test for the property 'Stars'
        }

        /// <summary>
        /// Test the property 'Rating'
        /// </summary>
        [Fact]
        public void RatingTest()
        {
            // TODO unit test for the property 'Rating'
        }

        /// <summary>
        /// Test the property 'HometownInfo'
        /// </summary>
        [Fact]
        public void HometownInfoTest()
        {
            // TODO unit test for the property 'HometownInfo'
        }

        /// <summary>
        /// Test the property 'AthleteId'
        /// </summary>
        [Fact]
        public void AthleteIdTest()
        {
            // TODO unit test for the property 'AthleteId'
        }

        /// <summary>
        /// Test the property 'Ranking'
        /// </summary>
        [Fact]
        public void RankingTest()
        {
            // TODO unit test for the property 'Ranking'
        }

        /// <summary>
        /// Test the property 'School'
        /// </summary>
        [Fact]
        public void SchoolTest()
        {
            // TODO unit test for the property 'School'
        }

        /// <summary>
        /// Test the property 'CommittedTo'
        /// </summary>
        [Fact]
        public void CommittedToTest()
        {
            // TODO unit test for the property 'CommittedTo'
        }

        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }

        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Fact]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'StateProvince'
        /// </summary>
        [Fact]
        public void StateProvinceTest()
        {
            // TODO unit test for the property 'StateProvince'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
    }
}
