/*
 * College Football Data API
 *
 * This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.
 *
 * The version of the OpenAPI document: 5.6.8
 * Contact: admin@collegefootballdata.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CollegeFootballData.Model;
using CollegeFootballData.Client;
using System.Reflection;

namespace CollegeFootballData.Test.Model
{
    /// <summary>
    ///  Class for testing RosterPlayer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RosterPlayerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RosterPlayer
        //private RosterPlayer instance;

        public RosterPlayerTests()
        {
            // TODO uncomment below to create an instance of RosterPlayer
            //instance = new RosterPlayer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RosterPlayer
        /// </summary>
        [Fact]
        public void RosterPlayerInstanceTest()
        {
            // TODO uncomment below to test "IsType" RosterPlayer
            //Assert.IsType<RosterPlayer>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'Team'
        /// </summary>
        [Fact]
        public void TeamTest()
        {
            // TODO unit test for the property 'Team'
        }

        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Fact]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }

        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Fact]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }

        /// <summary>
        /// Test the property 'Jersey'
        /// </summary>
        [Fact]
        public void JerseyTest()
        {
            // TODO unit test for the property 'Jersey'
        }

        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }

        /// <summary>
        /// Test the property 'HomeCity'
        /// </summary>
        [Fact]
        public void HomeCityTest()
        {
            // TODO unit test for the property 'HomeCity'
        }

        /// <summary>
        /// Test the property 'HomeState'
        /// </summary>
        [Fact]
        public void HomeStateTest()
        {
            // TODO unit test for the property 'HomeState'
        }

        /// <summary>
        /// Test the property 'HomeCountry'
        /// </summary>
        [Fact]
        public void HomeCountryTest()
        {
            // TODO unit test for the property 'HomeCountry'
        }

        /// <summary>
        /// Test the property 'HomeLatitude'
        /// </summary>
        [Fact]
        public void HomeLatitudeTest()
        {
            // TODO unit test for the property 'HomeLatitude'
        }

        /// <summary>
        /// Test the property 'HomeLongitude'
        /// </summary>
        [Fact]
        public void HomeLongitudeTest()
        {
            // TODO unit test for the property 'HomeLongitude'
        }

        /// <summary>
        /// Test the property 'HomeCountyFIPS'
        /// </summary>
        [Fact]
        public void HomeCountyFIPSTest()
        {
            // TODO unit test for the property 'HomeCountyFIPS'
        }

        /// <summary>
        /// Test the property 'RecruitIds'
        /// </summary>
        [Fact]
        public void RecruitIdsTest()
        {
            // TODO unit test for the property 'RecruitIds'
        }
    }
}
