/*
 * College Football Data API
 *
 * This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.
 *
 * The version of the OpenAPI document: 5.6.22
 * Contact: admin@collegefootballdata.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CollegeFootballData.Model;
using CollegeFootballData.Client;
using System.Reflection;

namespace CollegeFootballData.Test.Model
{
    /// <summary>
    ///  Class for testing ScoreboardGame
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScoreboardGameTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScoreboardGame
        //private ScoreboardGame instance;

        public ScoreboardGameTests()
        {
            // TODO uncomment below to create an instance of ScoreboardGame
            //instance = new ScoreboardGame();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScoreboardGame
        /// </summary>
        [Fact]
        public void ScoreboardGameInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScoreboardGame
            //Assert.IsType<ScoreboardGame>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }

        /// <summary>
        /// Test the property 'StartTimeTBD'
        /// </summary>
        [Fact]
        public void StartTimeTBDTest()
        {
            // TODO unit test for the property 'StartTimeTBD'
        }

        /// <summary>
        /// Test the property 'NeutralSite'
        /// </summary>
        [Fact]
        public void NeutralSiteTest()
        {
            // TODO unit test for the property 'NeutralSite'
        }

        /// <summary>
        /// Test the property 'ConferenceGame'
        /// </summary>
        [Fact]
        public void ConferenceGameTest()
        {
            // TODO unit test for the property 'ConferenceGame'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Venue'
        /// </summary>
        [Fact]
        public void VenueTest()
        {
            // TODO unit test for the property 'Venue'
        }

        /// <summary>
        /// Test the property 'HomeTeam'
        /// </summary>
        [Fact]
        public void HomeTeamTest()
        {
            // TODO unit test for the property 'HomeTeam'
        }

        /// <summary>
        /// Test the property 'AwayTeam'
        /// </summary>
        [Fact]
        public void AwayTeamTest()
        {
            // TODO unit test for the property 'AwayTeam'
        }

        /// <summary>
        /// Test the property 'Weather'
        /// </summary>
        [Fact]
        public void WeatherTest()
        {
            // TODO unit test for the property 'Weather'
        }

        /// <summary>
        /// Test the property 'Betting'
        /// </summary>
        [Fact]
        public void BettingTest()
        {
            // TODO unit test for the property 'Betting'
        }

        /// <summary>
        /// Test the property 'Tv'
        /// </summary>
        [Fact]
        public void TvTest()
        {
            // TODO unit test for the property 'Tv'
        }

        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Fact]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }

        /// <summary>
        /// Test the property 'Clock'
        /// </summary>
        [Fact]
        public void ClockTest()
        {
            // TODO unit test for the property 'Clock'
        }

        /// <summary>
        /// Test the property 'Situation'
        /// </summary>
        [Fact]
        public void SituationTest()
        {
            // TODO unit test for the property 'Situation'
        }

        /// <summary>
        /// Test the property 'Possession'
        /// </summary>
        [Fact]
        public void PossessionTest()
        {
            // TODO unit test for the property 'Possession'
        }

        /// <summary>
        /// Test the property 'LastPlay'
        /// </summary>
        [Fact]
        public void LastPlayTest()
        {
            // TODO unit test for the property 'LastPlay'
        }
    }
}
