/*
 * College Football Data API
 *
 * This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.
 *
 * The version of the OpenAPI document: 5.6.15
 * Contact: admin@collegefootballdata.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CollegeFootballData.Model;
using CollegeFootballData.Client;
using System.Reflection;

namespace CollegeFootballData.Test.Model
{
    /// <summary>
    ///  Class for testing TeamGamePredictedPointsAdded
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TeamGamePredictedPointsAddedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TeamGamePredictedPointsAdded
        //private TeamGamePredictedPointsAdded instance;

        public TeamGamePredictedPointsAddedTests()
        {
            // TODO uncomment below to create an instance of TeamGamePredictedPointsAdded
            //instance = new TeamGamePredictedPointsAdded();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TeamGamePredictedPointsAdded
        /// </summary>
        [Fact]
        public void TeamGamePredictedPointsAddedInstanceTest()
        {
            // TODO uncomment below to test "IsType" TeamGamePredictedPointsAdded
            //Assert.IsType<TeamGamePredictedPointsAdded>(instance);
        }

        /// <summary>
        /// Test the property 'GameId'
        /// </summary>
        [Fact]
        public void GameIdTest()
        {
            // TODO unit test for the property 'GameId'
        }

        /// <summary>
        /// Test the property 'Season'
        /// </summary>
        [Fact]
        public void SeasonTest()
        {
            // TODO unit test for the property 'Season'
        }

        /// <summary>
        /// Test the property 'Week'
        /// </summary>
        [Fact]
        public void WeekTest()
        {
            // TODO unit test for the property 'Week'
        }

        /// <summary>
        /// Test the property 'SeasonType'
        /// </summary>
        [Fact]
        public void SeasonTypeTest()
        {
            // TODO unit test for the property 'SeasonType'
        }

        /// <summary>
        /// Test the property 'Team'
        /// </summary>
        [Fact]
        public void TeamTest()
        {
            // TODO unit test for the property 'Team'
        }

        /// <summary>
        /// Test the property 'Conference'
        /// </summary>
        [Fact]
        public void ConferenceTest()
        {
            // TODO unit test for the property 'Conference'
        }

        /// <summary>
        /// Test the property 'Opponent'
        /// </summary>
        [Fact]
        public void OpponentTest()
        {
            // TODO unit test for the property 'Opponent'
        }

        /// <summary>
        /// Test the property 'Offense'
        /// </summary>
        [Fact]
        public void OffenseTest()
        {
            // TODO unit test for the property 'Offense'
        }

        /// <summary>
        /// Test the property 'Defense'
        /// </summary>
        [Fact]
        public void DefenseTest()
        {
            // TODO unit test for the property 'Defense'
        }
    }
}
