// <auto-generated/>
#pragma warning disable CS0618
using CollegeFootballData.Rushing.Players;
using CollegeFootballData.Rushing.Plays;
using CollegeFootballData.Rushing.Teams;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CollegeFootballData.Rushing
{
    /// <summary>
    /// Builds and executes requests for operations under \rushing
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RushingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The players property</summary>
        public global::CollegeFootballData.Rushing.Players.PlayersRequestBuilder Players
        {
            get => new global::CollegeFootballData.Rushing.Players.PlayersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The plays property</summary>
        public global::CollegeFootballData.Rushing.Plays.PlaysRequestBuilder Plays
        {
            get => new global::CollegeFootballData.Rushing.Plays.PlaysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The teams property</summary>
        public global::CollegeFootballData.Rushing.Teams.TeamsRequestBuilder Teams
        {
            get => new global::CollegeFootballData.Rushing.Teams.TeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CollegeFootballData.Rushing.RushingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RushingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rushing", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CollegeFootballData.Rushing.RushingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RushingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rushing", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
