// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace CollegeFootballData.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TeamPPA : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The overall property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CollegeFootballData.Models.StatsByQuarter? Overall { get; set; }
#nullable restore
#else
        public global::CollegeFootballData.Models.StatsByQuarter Overall { get; set; }
#endif
        /// <summary>The passing property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CollegeFootballData.Models.StatsByQuarter? Passing { get; set; }
#nullable restore
#else
        public global::CollegeFootballData.Models.StatsByQuarter Passing { get; set; }
#endif
        /// <summary>The plays property</summary>
        public int? Plays { get; set; }
        /// <summary>The rushing property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CollegeFootballData.Models.StatsByQuarter? Rushing { get; set; }
#nullable restore
#else
        public global::CollegeFootballData.Models.StatsByQuarter Rushing { get; set; }
#endif
        /// <summary>The team property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Team { get; set; }
#nullable restore
#else
        public string Team { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::CollegeFootballData.Models.TeamPPA"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::CollegeFootballData.Models.TeamPPA CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::CollegeFootballData.Models.TeamPPA();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "overall", n => { Overall = n.GetObjectValue<global::CollegeFootballData.Models.StatsByQuarter>(global::CollegeFootballData.Models.StatsByQuarter.CreateFromDiscriminatorValue); } },
                { "passing", n => { Passing = n.GetObjectValue<global::CollegeFootballData.Models.StatsByQuarter>(global::CollegeFootballData.Models.StatsByQuarter.CreateFromDiscriminatorValue); } },
                { "plays", n => { Plays = n.GetIntValue(); } },
                { "rushing", n => { Rushing = n.GetObjectValue<global::CollegeFootballData.Models.StatsByQuarter>(global::CollegeFootballData.Models.StatsByQuarter.CreateFromDiscriminatorValue); } },
                { "team", n => { Team = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::CollegeFootballData.Models.StatsByQuarter>("overall", Overall);
            writer.WriteObjectValue<global::CollegeFootballData.Models.StatsByQuarter>("passing", Passing);
            writer.WriteIntValue("plays", Plays);
            writer.WriteObjectValue<global::CollegeFootballData.Models.StatsByQuarter>("rushing", Rushing);
            writer.WriteStringValue("team", Team);
        }
    }
}
#pragma warning restore CS0618
