// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace CollegeFootballData.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TeamFPI_resumeRanks : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The averageWinProbability property</summary>
        public int? AverageWinProbability { get; set; }
        /// <summary>The fpi property</summary>
        public int? Fpi { get; set; }
        /// <summary>The gameControl property</summary>
        public int? GameControl { get; set; }
        /// <summary>The remainingStrengthOfSchedule property</summary>
        public int? RemainingStrengthOfSchedule { get; set; }
        /// <summary>The strengthOfRecord property</summary>
        public int? StrengthOfRecord { get; set; }
        /// <summary>The strengthOfSchedule property</summary>
        public int? StrengthOfSchedule { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::CollegeFootballData.Models.TeamFPI_resumeRanks"/> and sets the default values.
        /// </summary>
        public TeamFPI_resumeRanks()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::CollegeFootballData.Models.TeamFPI_resumeRanks"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::CollegeFootballData.Models.TeamFPI_resumeRanks CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::CollegeFootballData.Models.TeamFPI_resumeRanks();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "averageWinProbability", n => { AverageWinProbability = n.GetIntValue(); } },
                { "fpi", n => { Fpi = n.GetIntValue(); } },
                { "gameControl", n => { GameControl = n.GetIntValue(); } },
                { "remainingStrengthOfSchedule", n => { RemainingStrengthOfSchedule = n.GetIntValue(); } },
                { "strengthOfRecord", n => { StrengthOfRecord = n.GetIntValue(); } },
                { "strengthOfSchedule", n => { StrengthOfSchedule = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("averageWinProbability", AverageWinProbability);
            writer.WriteIntValue("fpi", Fpi);
            writer.WriteIntValue("gameControl", GameControl);
            writer.WriteIntValue("remainingStrengthOfSchedule", RemainingStrengthOfSchedule);
            writer.WriteIntValue("strengthOfRecord", StrengthOfRecord);
            writer.WriteIntValue("strengthOfSchedule", StrengthOfSchedule);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
