// <auto-generated/>
#pragma warning disable CS0618
using CollegeFootballData.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace CollegeFootballData.Stats.Season.Advanced
{
    /// <summary>
    /// Builds and executes requests for operations under \stats\season\advanced
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AdvancedRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::CollegeFootballData.Stats.Season.Advanced.AdvancedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdvancedRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/stats/season/advanced{?classification*,endWeek*,excludeGarbageTime*,startWeek*,team*,year*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CollegeFootballData.Stats.Season.Advanced.AdvancedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdvancedRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/stats/season/advanced{?classification*,endWeek*,excludeGarbageTime*,startWeek*,team*,year*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns advanced team statistics aggregated by season.
        /// </summary>
        /// <returns>A List&lt;global::CollegeFootballData.Models.AdvancedSeasonStat&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::CollegeFootballData.Models.AdvancedSeasonStat>?> GetAsync(Action<RequestConfiguration<global::CollegeFootballData.Stats.Season.Advanced.AdvancedRequestBuilder.AdvancedRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::CollegeFootballData.Models.AdvancedSeasonStat>> GetAsync(Action<RequestConfiguration<global::CollegeFootballData.Stats.Season.Advanced.AdvancedRequestBuilder.AdvancedRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::CollegeFootballData.Models.AdvancedSeasonStat>(requestInfo, global::CollegeFootballData.Models.AdvancedSeasonStat.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Returns advanced team statistics aggregated by season.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::CollegeFootballData.Stats.Season.Advanced.AdvancedRequestBuilder.AdvancedRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::CollegeFootballData.Stats.Season.Advanced.AdvancedRequestBuilder.AdvancedRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::CollegeFootballData.Stats.Season.Advanced.AdvancedRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::CollegeFootballData.Stats.Season.Advanced.AdvancedRequestBuilder WithUrl(string rawUrl)
        {
            return new global::CollegeFootballData.Stats.Season.Advanced.AdvancedRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns advanced team statistics aggregated by season.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AdvancedRequestBuilderGetQueryParameters 
        {
            /// <summary>Division classification. Defaults to `fbs`.</summary>
            [Obsolete("This property is deprecated, use ClassificationAsDivisionClassification instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("classification")]
            public string? Classification { get; set; }
#nullable restore
#else
            [QueryParameter("classification")]
            public string Classification { get; set; }
#endif
            /// <summary>Division classification. Defaults to `fbs`.</summary>
            [QueryParameter("classification")]
            public global::CollegeFootballData.Models.DivisionClassification? ClassificationAsDivisionClassification { get; set; }
            /// <summary>Latest week to include.</summary>
            [QueryParameter("endWeek")]
            public int? EndWeek { get; set; }
            /// <summary>Excludes garbage-time plays when `true`. Defaultsto `false`.</summary>
            [QueryParameter("excludeGarbageTime")]
            public bool? ExcludeGarbageTime { get; set; }
            /// <summary>Earliest week to include.</summary>
            [QueryParameter("startWeek")]
            public int? StartWeek { get; set; }
            /// <summary>Team name. Required unless `year` is specified.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("team")]
            public string? Team { get; set; }
#nullable restore
#else
            [QueryParameter("team")]
            public string Team { get; set; }
#endif
            /// <summary>Season year. Required unless `team` is specified.</summary>
            [QueryParameter("year")]
            public int? Year { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AdvancedRequestBuilderGetRequestConfiguration : RequestConfiguration<global::CollegeFootballData.Stats.Season.Advanced.AdvancedRequestBuilder.AdvancedRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
