// <auto-generated/>
#pragma warning disable CS0618
using CollegeFootballData.Models;
using CollegeFootballData.Stats.Player.Success.Game;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace CollegeFootballData.Stats.Player.Success
{
    /// <summary>
    /// Builds and executes requests for operations under \stats\player\success
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SuccessRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The game property</summary>
        public global::CollegeFootballData.Stats.Player.Success.Game.GameRequestBuilder Game
        {
            get => new global::CollegeFootballData.Stats.Player.Success.Game.GameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CollegeFootballData.Stats.Player.Success.SuccessRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SuccessRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/stats/player/success{?conference*,endWeek*,excludeGarbageTime*,playerId*,seasonType*,startWeek*,team*,threshold*,year*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CollegeFootballData.Stats.Player.Success.SuccessRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SuccessRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/stats/player/success{?conference*,endWeek*,excludeGarbageTime*,playerId*,seasonType*,startWeek*,team*,threshold*,year*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns player passing and rushing success rates by season.
        /// </summary>
        /// <returns>A List&lt;global::CollegeFootballData.Models.PlayerSeasonSuccessRate&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::CollegeFootballData.Models.PlayerSeasonSuccessRate>?> GetAsync(Action<RequestConfiguration<global::CollegeFootballData.Stats.Player.Success.SuccessRequestBuilder.SuccessRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::CollegeFootballData.Models.PlayerSeasonSuccessRate>> GetAsync(Action<RequestConfiguration<global::CollegeFootballData.Stats.Player.Success.SuccessRequestBuilder.SuccessRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::CollegeFootballData.Models.PlayerSeasonSuccessRate>(requestInfo, global::CollegeFootballData.Models.PlayerSeasonSuccessRate.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Returns player passing and rushing success rates by season.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::CollegeFootballData.Stats.Player.Success.SuccessRequestBuilder.SuccessRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::CollegeFootballData.Stats.Player.Success.SuccessRequestBuilder.SuccessRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::CollegeFootballData.Stats.Player.Success.SuccessRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::CollegeFootballData.Stats.Player.Success.SuccessRequestBuilder WithUrl(string rawUrl)
        {
            return new global::CollegeFootballData.Stats.Player.Success.SuccessRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns player passing and rushing success rates by season.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SuccessRequestBuilderGetQueryParameters 
        {
            /// <summary>Conference abbreviation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("conference")]
            public string? Conference { get; set; }
#nullable restore
#else
            [QueryParameter("conference")]
            public string Conference { get; set; }
#endif
            /// <summary>Latest week to include.</summary>
            [QueryParameter("endWeek")]
            public int? EndWeek { get; set; }
            /// <summary>Excludes garbage-time plays when `true`.</summary>
            [QueryParameter("excludeGarbageTime")]
            public bool? ExcludeGarbageTime { get; set; }
            /// <summary>Player ID. Required unless `year` is specified.</summary>
            [QueryParameter("playerId")]
            public int? PlayerId { get; set; }
            /// <summary>Season type.</summary>
            [Obsolete("This property is deprecated, use SeasonTypeAsSeasonType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("seasonType")]
            public string? SeasonType { get; set; }
#nullable restore
#else
            [QueryParameter("seasonType")]
            public string SeasonType { get; set; }
#endif
            /// <summary>Season type.</summary>
            [QueryParameter("seasonType")]
            public global::CollegeFootballData.Models.SeasonType? SeasonTypeAsSeasonType { get; set; }
            /// <summary>Earliest week to include.</summary>
            [QueryParameter("startWeek")]
            public int? StartWeek { get; set; }
            /// <summary>Team name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("team")]
            public string? Team { get; set; }
#nullable restore
#else
            [QueryParameter("team")]
            public string Team { get; set; }
#endif
            /// <summary>Minimum credited passing and rushing plays.</summary>
            [QueryParameter("threshold")]
            public int? Threshold { get; set; }
            /// <summary>Season year. Required unless `playerId` is specified.</summary>
            [QueryParameter("year")]
            public int? Year { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SuccessRequestBuilderGetRequestConfiguration : RequestConfiguration<global::CollegeFootballData.Stats.Player.Success.SuccessRequestBuilder.SuccessRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
