// <auto-generated/>
#pragma warning disable CS0618
using CollegeFootballData.Ppa.Players.Games;
using CollegeFootballData.Ppa.Players.Season;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CollegeFootballData.Ppa.Players
{
    /// <summary>
    /// Builds and executes requests for operations under \ppa\players
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlayersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The games property</summary>
        public global::CollegeFootballData.Ppa.Players.Games.GamesRequestBuilder Games
        {
            get => new global::CollegeFootballData.Ppa.Players.Games.GamesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The season property</summary>
        public global::CollegeFootballData.Ppa.Players.Season.SeasonRequestBuilder Season
        {
            get => new global::CollegeFootballData.Ppa.Players.Season.SeasonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CollegeFootballData.Ppa.Players.PlayersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlayersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ppa/players", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CollegeFootballData.Ppa.Players.PlayersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlayersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ppa/players", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
