// <auto-generated/>
#pragma warning disable CS0618
using CollegeFootballData.Player.Portal;
using CollegeFootballData.Player.Returning;
using CollegeFootballData.Player.Search;
using CollegeFootballData.Player.Usage;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CollegeFootballData.Player
{
    /// <summary>
    /// Builds and executes requests for operations under \player
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlayerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The portal property</summary>
        public global::CollegeFootballData.Player.Portal.PortalRequestBuilder Portal
        {
            get => new global::CollegeFootballData.Player.Portal.PortalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The returning property</summary>
        public global::CollegeFootballData.Player.Returning.ReturningRequestBuilder Returning
        {
            get => new global::CollegeFootballData.Player.Returning.ReturningRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::CollegeFootballData.Player.Search.SearchRequestBuilder Search
        {
            get => new global::CollegeFootballData.Player.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The usage property</summary>
        public global::CollegeFootballData.Player.Usage.UsageRequestBuilder Usage
        {
            get => new global::CollegeFootballData.Player.Usage.UsageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CollegeFootballData.Player.PlayerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlayerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/player", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CollegeFootballData.Player.PlayerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlayerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/player", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
