// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace CollegeFootballData.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CoachTenure : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active property</summary>
        public bool? Active { get; set; }
        /// <summary>The attributionComplete property</summary>
        public bool? AttributionComplete { get; set; }
        /// <summary>The coach property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CollegeFootballData.Models.CoachReference? Coach { get; set; }
#nullable restore
#else
        public global::CollegeFootballData.Models.CoachReference Coach { get; set; }
#endif
        /// <summary>The effectiveEnd property</summary>
        public DateTimeOffset? EffectiveEnd { get; set; }
        /// <summary>The effectiveStart property</summary>
        public DateTimeOffset? EffectiveStart { get; set; }
        /// <summary>The endYear property</summary>
        public int? EndYear { get; set; }
        /// <summary>The hireDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HireDate { get; set; }
#nullable restore
#else
        public string HireDate { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The isInterim property</summary>
        public bool? IsInterim { get; set; }
        /// <summary>The record property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CollegeFootballData.Models.CoachRecord? Record { get; set; }
#nullable restore
#else
        public global::CollegeFootballData.Models.CoachRecord Record { get; set; }
#endif
        /// <summary>The seasons property</summary>
        public int? Seasons { get; set; }
        /// <summary>The startYear property</summary>
        public int? StartYear { get; set; }
        /// <summary>The team property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CollegeFootballData.Models.CoachTeamReference? Team { get; set; }
#nullable restore
#else
        public global::CollegeFootballData.Models.CoachTeamReference Team { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::CollegeFootballData.Models.CoachTenure"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::CollegeFootballData.Models.CoachTenure CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::CollegeFootballData.Models.CoachTenure();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "attributionComplete", n => { AttributionComplete = n.GetBoolValue(); } },
                { "coach", n => { Coach = n.GetObjectValue<global::CollegeFootballData.Models.CoachReference>(global::CollegeFootballData.Models.CoachReference.CreateFromDiscriminatorValue); } },
                { "effectiveEnd", n => { EffectiveEnd = n.GetDateTimeOffsetValue(); } },
                { "effectiveStart", n => { EffectiveStart = n.GetDateTimeOffsetValue(); } },
                { "endYear", n => { EndYear = n.GetIntValue(); } },
                { "hireDate", n => { HireDate = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "isInterim", n => { IsInterim = n.GetBoolValue(); } },
                { "record", n => { Record = n.GetObjectValue<global::CollegeFootballData.Models.CoachRecord>(global::CollegeFootballData.Models.CoachRecord.CreateFromDiscriminatorValue); } },
                { "seasons", n => { Seasons = n.GetIntValue(); } },
                { "startYear", n => { StartYear = n.GetIntValue(); } },
                { "team", n => { Team = n.GetObjectValue<global::CollegeFootballData.Models.CoachTeamReference>(global::CollegeFootballData.Models.CoachTeamReference.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteBoolValue("attributionComplete", AttributionComplete);
            writer.WriteObjectValue<global::CollegeFootballData.Models.CoachReference>("coach", Coach);
            writer.WriteDateTimeOffsetValue("effectiveEnd", EffectiveEnd);
            writer.WriteDateTimeOffsetValue("effectiveStart", EffectiveStart);
            writer.WriteIntValue("endYear", EndYear);
            writer.WriteStringValue("hireDate", HireDate);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("isInterim", IsInterim);
            writer.WriteObjectValue<global::CollegeFootballData.Models.CoachRecord>("record", Record);
            writer.WriteIntValue("seasons", Seasons);
            writer.WriteIntValue("startYear", StartYear);
            writer.WriteObjectValue<global::CollegeFootballData.Models.CoachTeamReference>("team", Team);
        }
    }
}
#pragma warning restore CS0618
