// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace CollegeFootballData.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CoachNotFound_message
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Coach not found")]
        #pragma warning disable CS1591
        CoachNotFound,
        #pragma warning restore CS1591
    }
}
