// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace CollegeFootballData.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PlayoffLinkedGame : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The awayPoints property</summary>
        public int? AwayPoints { get; set; }
        /// <summary>The awayTeam property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CollegeFootballData.Models.PlayoffTeam? AwayTeam { get; set; }
#nullable restore
#else
        public global::CollegeFootballData.Models.PlayoffTeam AwayTeam { get; set; }
#endif
        /// <summary>The completed property</summary>
        public bool? Completed { get; set; }
        /// <summary>The homePoints property</summary>
        public int? HomePoints { get; set; }
        /// <summary>The homeTeam property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CollegeFootballData.Models.PlayoffTeam? HomeTeam { get; set; }
#nullable restore
#else
        public global::CollegeFootballData.Models.PlayoffTeam HomeTeam { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The startDate property</summary>
        public DateTimeOffset? StartDate { get; set; }
        /// <summary>The venue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Venue { get; set; }
#nullable restore
#else
        public string Venue { get; set; }
#endif
        /// <summary>The venueId property</summary>
        public int? VenueId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::CollegeFootballData.Models.PlayoffLinkedGame"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::CollegeFootballData.Models.PlayoffLinkedGame CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::CollegeFootballData.Models.PlayoffLinkedGame();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "awayPoints", n => { AwayPoints = n.GetIntValue(); } },
                { "awayTeam", n => { AwayTeam = n.GetObjectValue<global::CollegeFootballData.Models.PlayoffTeam>(global::CollegeFootballData.Models.PlayoffTeam.CreateFromDiscriminatorValue); } },
                { "completed", n => { Completed = n.GetBoolValue(); } },
                { "homePoints", n => { HomePoints = n.GetIntValue(); } },
                { "homeTeam", n => { HomeTeam = n.GetObjectValue<global::CollegeFootballData.Models.PlayoffTeam>(global::CollegeFootballData.Models.PlayoffTeam.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "startDate", n => { StartDate = n.GetDateTimeOffsetValue(); } },
                { "venue", n => { Venue = n.GetStringValue(); } },
                { "venueId", n => { VenueId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("awayPoints", AwayPoints);
            writer.WriteObjectValue<global::CollegeFootballData.Models.PlayoffTeam>("awayTeam", AwayTeam);
            writer.WriteBoolValue("completed", Completed);
            writer.WriteIntValue("homePoints", HomePoints);
            writer.WriteObjectValue<global::CollegeFootballData.Models.PlayoffTeam>("homeTeam", HomeTeam);
            writer.WriteIntValue("id", Id);
            writer.WriteDateTimeOffsetValue("startDate", StartDate);
            writer.WriteStringValue("venue", Venue);
            writer.WriteIntValue("venueId", VenueId);
        }
    }
}
#pragma warning restore CS0618
