// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace CollegeFootballData.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PreviewSection_SeriesHistory__status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "available")]
        #pragma warning disable CS1591
        Available,
        #pragma warning restore CS1591
        [EnumMember(Value = "no_data")]
        #pragma warning disable CS1591
        No_data,
        #pragma warning restore CS1591
        [EnumMember(Value = "unavailable")]
        #pragma warning disable CS1591
        Unavailable,
        #pragma warning restore CS1591
    }
}
