// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace CollegeFootballData.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ScheduleGame : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The awayTeam property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CollegeFootballData.Models.PreviewTeamIdentity? AwayTeam { get; set; }
#nullable restore
#else
        public global::CollegeFootballData.Models.PreviewTeamIdentity AwayTeam { get; set; }
#endif
        /// <summary>The broadcasts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CollegeFootballData.Models.PreviewSection_PreviewBroadcastArray_? Broadcasts { get; set; }
#nullable restore
#else
        public global::CollegeFootballData.Models.PreviewSection_PreviewBroadcastArray_ Broadcasts { get; set; }
#endif
        /// <summary>The conferenceGame property</summary>
        public bool? ConferenceGame { get; set; }
        /// <summary>The homeTeam property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CollegeFootballData.Models.PreviewTeamIdentity? HomeTeam { get; set; }
#nullable restore
#else
        public global::CollegeFootballData.Models.PreviewTeamIdentity HomeTeam { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The neutralSite property</summary>
        public bool? NeutralSite { get; set; }
        /// <summary>The odds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CollegeFootballData.Models.PreviewSection_SelectedOdds_? Odds { get; set; }
#nullable restore
#else
        public global::CollegeFootballData.Models.PreviewSection_SelectedOdds_ Odds { get; set; }
#endif
        /// <summary>The playoff property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CollegeFootballData.Models.GamePlayoff? Playoff { get; set; }
#nullable restore
#else
        public global::CollegeFootballData.Models.GamePlayoff Playoff { get; set; }
#endif
        /// <summary>The season property</summary>
        public int? Season { get; set; }
        /// <summary>The seasonType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CollegeFootballData.Models.ScheduleGame.ScheduleGame_seasonType? SeasonType { get; set; }
#nullable restore
#else
        public global::CollegeFootballData.Models.ScheduleGame.ScheduleGame_seasonType SeasonType { get; set; }
#endif
        /// <summary>The startDate property</summary>
        public DateTimeOffset? StartDate { get; set; }
        /// <summary>The startTimeTBD property</summary>
        public bool? StartTimeTBD { get; set; }
        /// <summary>The status property</summary>
        public global::CollegeFootballData.Models.GameStatus? Status { get; set; }
        /// <summary>The statusCheckedAt property</summary>
        public DateTimeOffset? StatusCheckedAt { get; set; }
        /// <summary>The venue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CollegeFootballData.Models.PreviewVenue? Venue { get; set; }
#nullable restore
#else
        public global::CollegeFootballData.Models.PreviewVenue Venue { get; set; }
#endif
        /// <summary>The week property</summary>
        public int? Week { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::CollegeFootballData.Models.ScheduleGame"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::CollegeFootballData.Models.ScheduleGame CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::CollegeFootballData.Models.ScheduleGame();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "awayTeam", n => { AwayTeam = n.GetObjectValue<global::CollegeFootballData.Models.PreviewTeamIdentity>(global::CollegeFootballData.Models.PreviewTeamIdentity.CreateFromDiscriminatorValue); } },
                { "broadcasts", n => { Broadcasts = n.GetObjectValue<global::CollegeFootballData.Models.PreviewSection_PreviewBroadcastArray_>(global::CollegeFootballData.Models.PreviewSection_PreviewBroadcastArray_.CreateFromDiscriminatorValue); } },
                { "conferenceGame", n => { ConferenceGame = n.GetBoolValue(); } },
                { "homeTeam", n => { HomeTeam = n.GetObjectValue<global::CollegeFootballData.Models.PreviewTeamIdentity>(global::CollegeFootballData.Models.PreviewTeamIdentity.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "neutralSite", n => { NeutralSite = n.GetBoolValue(); } },
                { "odds", n => { Odds = n.GetObjectValue<global::CollegeFootballData.Models.PreviewSection_SelectedOdds_>(global::CollegeFootballData.Models.PreviewSection_SelectedOdds_.CreateFromDiscriminatorValue); } },
                { "playoff", n => { Playoff = n.GetObjectValue<global::CollegeFootballData.Models.GamePlayoff>(global::CollegeFootballData.Models.GamePlayoff.CreateFromDiscriminatorValue); } },
                { "season", n => { Season = n.GetIntValue(); } },
                { "seasonType", n => { SeasonType = n.GetObjectValue<global::CollegeFootballData.Models.ScheduleGame.ScheduleGame_seasonType>(global::CollegeFootballData.Models.ScheduleGame.ScheduleGame_seasonType.CreateFromDiscriminatorValue); } },
                { "startDate", n => { StartDate = n.GetDateTimeOffsetValue(); } },
                { "startTimeTBD", n => { StartTimeTBD = n.GetBoolValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::CollegeFootballData.Models.GameStatus>(); } },
                { "statusCheckedAt", n => { StatusCheckedAt = n.GetDateTimeOffsetValue(); } },
                { "venue", n => { Venue = n.GetObjectValue<global::CollegeFootballData.Models.PreviewVenue>(global::CollegeFootballData.Models.PreviewVenue.CreateFromDiscriminatorValue); } },
                { "week", n => { Week = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::CollegeFootballData.Models.PreviewTeamIdentity>("awayTeam", AwayTeam);
            writer.WriteObjectValue<global::CollegeFootballData.Models.PreviewSection_PreviewBroadcastArray_>("broadcasts", Broadcasts);
            writer.WriteBoolValue("conferenceGame", ConferenceGame);
            writer.WriteObjectValue<global::CollegeFootballData.Models.PreviewTeamIdentity>("homeTeam", HomeTeam);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("neutralSite", NeutralSite);
            writer.WriteObjectValue<global::CollegeFootballData.Models.PreviewSection_SelectedOdds_>("odds", Odds);
            writer.WriteObjectValue<global::CollegeFootballData.Models.GamePlayoff>("playoff", Playoff);
            writer.WriteIntValue("season", Season);
            writer.WriteObjectValue<global::CollegeFootballData.Models.ScheduleGame.ScheduleGame_seasonType>("seasonType", SeasonType);
            writer.WriteDateTimeOffsetValue("startDate", StartDate);
            writer.WriteBoolValue("startTimeTBD", StartTimeTBD);
            writer.WriteEnumValue<global::CollegeFootballData.Models.GameStatus>("status", Status);
            writer.WriteDateTimeOffsetValue("statusCheckedAt", StatusCheckedAt);
            writer.WriteObjectValue<global::CollegeFootballData.Models.PreviewVenue>("venue", Venue);
            writer.WriteIntValue("week", Week);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::CollegeFootballData.Models.SeasonType"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ScheduleGame_seasonType : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::CollegeFootballData.Models.SeasonType"/></summary>
            public global::CollegeFootballData.Models.SeasonType? SeasonType { get; set; }
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::CollegeFootballData.Models.ScheduleGame.ScheduleGame_seasonType"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::CollegeFootballData.Models.ScheduleGame.ScheduleGame_seasonType CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::CollegeFootballData.Models.ScheduleGame.ScheduleGame_seasonType();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else if(parseNode.GetEnumValue<global::CollegeFootballData.Models.SeasonType>() is global::CollegeFootballData.Models.SeasonType seasonTypeValue)
                {
                    result.SeasonType = seasonTypeValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else if(SeasonType != null)
                {
                    writer.WriteEnumValue<global::CollegeFootballData.Models.SeasonType>(null, SeasonType);
                }
            }
        }
    }
}
#pragma warning restore CS0618
