/*
 * College Football Data API
 *
 * This is an API for query various college football datasets and analytics. API keys can be acquired from the CollegeFootballData.com website.
 *
 * The version of the OpenAPI document: 5.5.1
 * Contact: admin@collegefootballdata.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = CollegeFootballData.Client.OpenAPIDateConverter;

namespace CollegeFootballData.Model
{
    /// <summary>
    /// PlayerGamePredictedPointsAdded
    /// </summary>
    [DataContract(Name = "PlayerGamePredictedPointsAdded")]
    public partial class PlayerGamePredictedPointsAdded : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets SeasonType
        /// </summary>
        [DataMember(Name = "seasonType", IsRequired = true, EmitDefaultValue = true)]
        public SeasonType SeasonType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerGamePredictedPointsAdded" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PlayerGamePredictedPointsAdded() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerGamePredictedPointsAdded" /> class.
        /// </summary>
        /// <param name="season">season (required).</param>
        /// <param name="week">week (required).</param>
        /// <param name="seasonType">seasonType (required).</param>
        /// <param name="id">id (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="position">position (required).</param>
        /// <param name="team">team (required).</param>
        /// <param name="opponent">opponent (required).</param>
        /// <param name="averagePPA">averagePPA (required).</param>
        public PlayerGamePredictedPointsAdded(int season = default(int), int week = default(int), SeasonType seasonType = default(SeasonType), string id = default(string), string name = default(string), string position = default(string), string team = default(string), string opponent = default(string), PlayerGamePredictedPointsAddedAveragePPA averagePPA = default(PlayerGamePredictedPointsAddedAveragePPA))
        {
            this.Season = season;
            this.Week = week;
            this.SeasonType = seasonType;
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for PlayerGamePredictedPointsAdded and cannot be null");
            }
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for PlayerGamePredictedPointsAdded and cannot be null");
            }
            this.Name = name;
            // to ensure "position" is required (not null)
            if (position == null)
            {
                throw new ArgumentNullException("position is a required property for PlayerGamePredictedPointsAdded and cannot be null");
            }
            this.Position = position;
            // to ensure "team" is required (not null)
            if (team == null)
            {
                throw new ArgumentNullException("team is a required property for PlayerGamePredictedPointsAdded and cannot be null");
            }
            this.Team = team;
            // to ensure "opponent" is required (not null)
            if (opponent == null)
            {
                throw new ArgumentNullException("opponent is a required property for PlayerGamePredictedPointsAdded and cannot be null");
            }
            this.Opponent = opponent;
            // to ensure "averagePPA" is required (not null)
            if (averagePPA == null)
            {
                throw new ArgumentNullException("averagePPA is a required property for PlayerGamePredictedPointsAdded and cannot be null");
            }
            this.AveragePPA = averagePPA;
        }

        /// <summary>
        /// Gets or Sets Season
        /// </summary>
        [DataMember(Name = "season", IsRequired = true, EmitDefaultValue = true)]
        public int Season { get; set; }

        /// <summary>
        /// Gets or Sets Week
        /// </summary>
        [DataMember(Name = "week", IsRequired = true, EmitDefaultValue = true)]
        public int Week { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Position
        /// </summary>
        [DataMember(Name = "position", IsRequired = true, EmitDefaultValue = true)]
        public string Position { get; set; }

        /// <summary>
        /// Gets or Sets Team
        /// </summary>
        [DataMember(Name = "team", IsRequired = true, EmitDefaultValue = true)]
        public string Team { get; set; }

        /// <summary>
        /// Gets or Sets Opponent
        /// </summary>
        [DataMember(Name = "opponent", IsRequired = true, EmitDefaultValue = true)]
        public string Opponent { get; set; }

        /// <summary>
        /// Gets or Sets AveragePPA
        /// </summary>
        [DataMember(Name = "averagePPA", IsRequired = true, EmitDefaultValue = true)]
        public PlayerGamePredictedPointsAddedAveragePPA AveragePPA { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlayerGamePredictedPointsAdded {\n");
            sb.Append("  Season: ").Append(Season).Append("\n");
            sb.Append("  Week: ").Append(Week).Append("\n");
            sb.Append("  SeasonType: ").Append(SeasonType).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Position: ").Append(Position).Append("\n");
            sb.Append("  Team: ").Append(Team).Append("\n");
            sb.Append("  Opponent: ").Append(Opponent).Append("\n");
            sb.Append("  AveragePPA: ").Append(AveragePPA).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
