// <auto-generated/>
#pragma warning disable CS0618
using CollegeFootballData.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace CollegeFootballData.Metrics.Wp.Pregame
{
    /// <summary>
    /// Builds and executes requests for operations under \metrics\wp\pregame
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PregameRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::CollegeFootballData.Metrics.Wp.Pregame.PregameRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PregameRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/metrics/wp/pregame{?seasonType*,team*,week*,year*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CollegeFootballData.Metrics.Wp.Pregame.PregameRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PregameRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/metrics/wp/pregame{?seasonType*,team*,week*,year*}", rawUrl)
        {
        }
        /// <summary>
        /// Queries pregame win probabilities
        /// </summary>
        /// <returns>A List&lt;global::CollegeFootballData.Models.PregameWinProbability&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::CollegeFootballData.Models.PregameWinProbability>?> GetAsync(Action<RequestConfiguration<global::CollegeFootballData.Metrics.Wp.Pregame.PregameRequestBuilder.PregameRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::CollegeFootballData.Models.PregameWinProbability>> GetAsync(Action<RequestConfiguration<global::CollegeFootballData.Metrics.Wp.Pregame.PregameRequestBuilder.PregameRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::CollegeFootballData.Models.PregameWinProbability>(requestInfo, global::CollegeFootballData.Models.PregameWinProbability.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Queries pregame win probabilities
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::CollegeFootballData.Metrics.Wp.Pregame.PregameRequestBuilder.PregameRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::CollegeFootballData.Metrics.Wp.Pregame.PregameRequestBuilder.PregameRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::CollegeFootballData.Metrics.Wp.Pregame.PregameRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::CollegeFootballData.Metrics.Wp.Pregame.PregameRequestBuilder WithUrl(string rawUrl)
        {
            return new global::CollegeFootballData.Metrics.Wp.Pregame.PregameRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Queries pregame win probabilities
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PregameRequestBuilderGetQueryParameters 
        {
            /// <summary>Optional season type filter</summary>
            [Obsolete("This property is deprecated, use SeasonTypeAsSeasonType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("seasonType")]
            public string? SeasonType { get; set; }
#nullable restore
#else
            [QueryParameter("seasonType")]
            public string SeasonType { get; set; }
#endif
            /// <summary>Optional season type filter</summary>
            [QueryParameter("seasonType")]
            public global::CollegeFootballData.Models.SeasonType? SeasonTypeAsSeasonType { get; set; }
            /// <summary>Optional team filter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("team")]
            public string? Team { get; set; }
#nullable restore
#else
            [QueryParameter("team")]
            public string Team { get; set; }
#endif
            /// <summary>Optional week filter</summary>
            [QueryParameter("week")]
            public int? Week { get; set; }
            /// <summary>Optional year filter</summary>
            [QueryParameter("year")]
            public int? Year { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PregameRequestBuilderGetRequestConfiguration : RequestConfiguration<global::CollegeFootballData.Metrics.Wp.Pregame.PregameRequestBuilder.PregameRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
